name: Autograding Tests
'on':
- push
- repository_dispatch
- workflow_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # ---  GODOT SETUP  ---
    - name: Checkout Private Test Script
      uses: actions/checkout@v4
      with:
        repository: McDowell-CSSD/cargo-scout-autograder
        token: ${{ secrets.TEACHER_PAT }}
        path: teacher_script_folder
    - name: Move Test Script
      run: mv teacher_script_folder/autotest.gd .
    - name: Download Godot 4.6
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_linux.x86_64.zip
        unzip Godot_v4.6-stable_linux.x86_64.zip
        mv Godot_v4.6-stable_linux.x86_64 godot_executable
        chmod +x godot_executable
    - name: Import Assets
      run: ./godot_executable --headless --editor --quit

    # ---  GITHUB CLASSROOM TESTS  ---
    - name: 'Test 1: Building a Collectible'
      id: test-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Test 1'           # This must match autograding.json
        command: TEST_MODE=1 ./godot_executable --headless -s autotest.gd
        timeout: 2
        max-score: 20
        
    - name: 'Test 2: Player Health'
      id: test-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Test 2'
        command: TEST_MODE=2 ./godot_executable --headless -s autotest.gd
        timeout: 2
        max-score: 20
        
    - name: 'Test 3: Spawning Collectibles'
      id: test-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Test 3'
        command: TEST_MODE=3 ./godot_executable --headless -s autotest.gd
        timeout: 2
        max-score: 20
        
    - name: 'Test 4: Fine Tuning (Boundaries & Layers)'
      id: test-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Test 4'
        command: TEST_MODE=4 ./godot_executable --headless -s autotest.gd
        timeout: 2
        max-score: 20
        
    - name: 'Test 5: Simple Animations (Tweens)'
      id: test-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Test 5'
        command: TEST_MODE=5 ./godot_executable --headless -s autotest.gd
        timeout: 2
        max-score: 20

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
        TEST-5_RESULTS: "${{steps.test-5.outputs.result}}"
      with:
        runners: test-1,test-2,test-3,test-4,test-5
